// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/uma-31/switchboard/agent/adapter/http/controller"
	"github.com/uma-31/switchboard/agent/domain/valueobject"
	"github.com/uma-31/switchboard/agent/infrastructure/http/gin"
)

// Injectors from gin_server.go:

func InitializeGinServer(computerInfo *valueobject.ComputerInfo, port *gin.ServerPort) (*gin.Server, error) {
	computerInfoController := controller.NewComputerInfoController(computerInfo)
	router := gin.NewRouter(computerInfoController)
	server, err := gin.NewServer(router, port)
	if err != nil {
		return nil, err
	}
	return server, nil
}
