computer:
  # コンピューターを識別するための ID です。
  # ~ を指定する場合、コンピューターの情報から自動的に生成された ID が使用されます。
  # 主に、マネージャーが提供する API でリソースを指定するために使用されます。
  #
  # 例: "desktop"
  id: ~
  # コンピューターの名前です。
  # ~ を指定する場合、コンピューターの情報から自動的に生成された名前が使用されます。
  # 主に、マネージャーが提供する UI で表示される名前として使用されます。
  #
  # 例: "デスクトップ"
  name: ~

# マネージャーとの通信に使用するポート番号です。
# 同一ネットワーク内で動作する他のエージェントやマネージャーと同じポート番号を指定する必要があります。
port: 11331
